//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmountsReceived
    {
        public int ID { get; set; }
        public Nullable<int> TheFinancerProjectsID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual TheFinancerProject TheFinancerProject { get; set; }
    }
}
