//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int IDX { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int ProjectProfile_ID { get; set; }
        public string FilePathX { get; set; }
    }
}
