//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsTb
    {
        public GroupsTb()
        {
            this.PeremissionsTbs = new HashSet<PeremissionsTb>();
            this.UserTbs = new HashSet<UserTb>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PeremissionsTb> PeremissionsTbs { get; set; }
        public virtual ICollection<UserTb> UserTbs { get; set; }
    }
}
