//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthlysalary
    {
        public int ID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> Formonth { get; set; }
        public Nullable<int> ProjectProfile_ID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ProjectProfile ProjectProfile { get; set; }
    }
}
