//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeremissionsTb
    {
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> UpDateUser { get; set; }
        public Nullable<int> AddProject { get; set; }
        public Nullable<int> DisplayExpenses { get; set; }
        public Nullable<int> CanPrint { get; set; }
        public Nullable<int> AddEmployee { get; set; }
        public Nullable<int> AddSuppliers { get; set; }
        public Nullable<int> AddFinncers { get; set; }
        public Nullable<int> EditEmployee { get; set; }
        public Nullable<int> DeleteEmployee { get; set; }
        public Nullable<int> EditFinncers { get; set; }
        public Nullable<int> DeleteFinncers { get; set; }
        public Nullable<int> EditSuppliers { get; set; }
        public Nullable<int> DeleteSuppliers { get; set; }
        public int EditProject { get; set; }
    
        public virtual GroupsTb GroupsTb { get; set; }
    }
}
