//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivity
    {
        public ProjectActivity()
        {
            this.ProjectSubActivities = new HashSet<ProjectSubActivity>();
        }
    
        public int ID { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public int ProjectProfile_ID { get; set; }
    
        public virtual ProjectProfile ProjectProfile { get; set; }
        public virtual ICollection<ProjectSubActivity> ProjectSubActivities { get; set; }
    }
}
