//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfile
    {
        public ProjectProfile()
        {
            this.AmountsReceiveds = new HashSet<AmountsReceived>();
            this.Contracts = new HashSet<Contract>();
            this.Monthlysalaries = new HashSet<Monthlysalary>();
            this.ProjectActivities = new HashSet<ProjectActivity>();
            this.ProjectControls = new HashSet<ProjectControl>();
            this.ProjectExpenses = new HashSet<ProjectExpens>();
            this.ProjectSubActivities = new HashSet<ProjectSubActivity>();
            this.TheDonorsProjects = new HashSet<TheDonorsProject>();
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<double> progress { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public string Coin { get; set; }
    
        public virtual ICollection<AmountsReceived> AmountsReceiveds { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Monthlysalary> Monthlysalaries { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities { get; set; }
        public virtual ICollection<ProjectControl> ProjectControls { get; set; }
        public virtual ICollection<ProjectExpens> ProjectExpenses { get; set; }
        public virtual ICollection<ProjectSubActivity> ProjectSubActivities { get; set; }
        public virtual ICollection<TheDonorsProject> TheDonorsProjects { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
    }
}
