//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfile
    {
        public ProjectProfile()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Contracts = new HashSet<Contract>();
            this.ProjectControls = new HashSet<ProjectControl>();
            this.TheFinancerProjects = new HashSet<TheFinancerProject>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public string Coin { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<ProjectControl> ProjectControls { get; set; }
        public virtual ICollection<TheFinancerProject> TheFinancerProjects { get; set; }
    }
}
