//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPermession
    {
        public SystemPermession()
        {
            this.UserPermessions = new HashSet<UserPermession>();
        }
    
        public int ID { get; set; }
        public string PermessionName { get; set; }
        public string Desription { get; set; }
    
        public virtual ICollection<UserPermession> UserPermessions { get; set; }
    }
}
