//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheFinancerProject
    {
        public TheFinancerProject()
        {
            this.AmountsReceiveds = new HashSet<AmountsReceived>();
        }
    
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int FinacerID { get; set; }
        public Nullable<double> TotalCost { get; set; }
    
        public virtual ICollection<AmountsReceived> AmountsReceiveds { get; set; }
        public virtual ProjectProfile ProjectProfile { get; set; }
        public virtual Thefinancier Thefinancier { get; set; }
    }
}
