//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTb
    {
        public UserTb()
        {
            this.ProjectControls = new HashSet<ProjectControl>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string TypeUser { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GroupsTb GroupsTb { get; set; }
        public virtual ICollection<ProjectControl> ProjectControls { get; set; }
    }
}
