//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermession
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int PermessioID { get; set; }
        public string PermessionValue { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual ProjectProfile ProjectProfile { get; set; }
        public virtual SystemPermession SystemPermession { get; set; }
        public virtual UserTb UserTb { get; set; }
    }
}
